def init_matplotlib():
    from matplotlib import rc
#    rc('font', **{'family': 'serif',
#                  'serif': ['Times', 'Times New Roman', 'Palatino'],
#                   'size': 8.0})


    # This does not make '-' ok
    # rc('font', **{'family': 'cmr10', 'size': 8.0})

    rc('font', **{'family': 'Bitstream Vera Serif', 'size': 8.0})

    #rc('text', usetex=True)
    # Crashes on lambda with:
    # RuntimeError: dvipng was not able to process the following file:                                                                     
# /home/andrea/.matplotlib/tex.cache/75ed870f776fb82987a80c0a1594890b.dvi                                                              
# Here is the full report generated by dvipng:    

#    rc('font', **{'family':'sans-serif',
#                  'sans-serif':['Arial'],
#                   'size': 8.0})
